<?php

return [
    'sales_email' => env('SOFTWARE_SALES_EMAIL', 'bill.humayun1@gmail.com'),
    'sales_phone' => env('SOFTWARE_SALES_PHONE', '+92 3003662818'),
    'products' => [
        'cloud-khata' => [
            'name' => 'Cloud Khata',
            'eyebrow' => 'Business & POS Management',
            'hero_focus' => 'everyday business clarity.',
            'tagline' => 'Run your business with clarity, from counter to accounts.',
            'description' => 'A complete cloud-based business and point-of-sale system that brings sales, purchases, inventory, customers, suppliers and financial reporting into one reliable workspace.',
            'icon' => 'cloud',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => null,
            'features' => [
                ['title' => 'Fast point of sale', 'description' => 'Create accurate bills, accept payments and keep every sale organized.'],
                ['title' => 'Inventory control', 'description' => 'Monitor stock, purchases, transfers and low-stock alerts in real time.'],
                ['title' => 'Business accounts', 'description' => 'Track customer and supplier ledgers, expenses, dues and cash flow.'],
                ['title' => 'Actionable reporting', 'description' => 'Understand sales, profit, stock and business performance from clear reports.'],
                ['title' => 'Multi-user operations', 'description' => 'Give team members the right access while keeping control of the business.'],
                ['title' => 'Cloud access', 'description' => 'Stay connected to your operation wherever business takes you.'],
            ],
        ],
        'vendify' => [
            'name' => 'Vendify',
            'eyebrow' => 'Retail & Service Management',
            'hero_focus' => 'modern retail and service businesses.',
            'tagline' => 'Run your entire business from one connected workspace.',
            'description' => 'A flexible POS and business management platform designed for shops, salons and service-based businesses. Manage sales, customers, inventory, employees, appointments, purchasing and daily operations without switching between multiple systems.',
            'icon' => 'store',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => 'https://pos.broshtech.com/demo',
            'features' => [
                ['title' => 'Smart POS & sales', 'description' => 'Process sales quickly, manage payments, apply coupons and keep every transaction organized in one place.'],
                ['title' => 'Inventory & purchasing', 'description' => 'Track products, stock levels, low-stock alerts, suppliers, purchases and stock adjustments with better visibility.'],
                ['title' => 'Staff & HR management', 'description' => 'Manage employees, roles, permissions, attendance, shifts, leave requests, salaries and staff performance.'],
                ['title' => 'Appointments & services', 'description' => 'Organize appointments, services, packages and staff availability through a simple shared workflow.'],
                ['title' => 'Customers & suppliers', 'description' => 'Keep useful customer and supplier records together with sales, purchase and transaction history.'],
                ['title' => 'Reports & business insights', 'description' => 'Monitor sales, inventory, attendance, salaries, customer purchases and staff performance through practical reports and dashboards.'],
            ],
        ],
        'cx-couriers' => [
            'name' => 'CX Couriers',
            'eyebrow' => 'Courier Operations',
            'hero_focus' => 'deliveries that keep moving.',
            'tagline' => 'Deliver every parcel with control, speed and visibility.',
            'description' => 'An end-to-end courier management system for organizing bookings, delivery teams, service routes, customers, cash collection and account ledgers from dispatch to final delivery.',
            'icon' => 'courier',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => null,
            'features' => [
                ['title' => 'Delivery workflow', 'description' => 'Manage consignments from booking and dispatch through delivery completion.'],
                ['title' => 'Rider management', 'description' => 'Assign deliveries and coordinate your delivery team efficiently.'],
                ['title' => 'Route organization', 'description' => 'Structure service areas and routes for smoother daily operations.'],
                ['title' => 'Customer management', 'description' => 'Maintain complete shipper and recipient information in one place.'],
                ['title' => 'Cash & ledgers', 'description' => 'Track collections, customer balances, expenses and account activity.'],
                ['title' => 'Delivery reporting', 'description' => 'See delivery status, performance and financial results clearly.'],
            ],
        ],
        'doms' => [
            'name' => 'DOMS',
            'eyebrow' => 'Distributed Order Management',
            'hero_focus' => 'orders that stay coordinated.',
            'tagline' => 'Turn spreadsheet orders into coordinated deliveries and clean accounts.',
            'description' => 'A distributed order management system that imports orders from Excel, assigns them to delivery staff by location and keeps delivery, ledger and financial records fully connected.',
            'icon' => 'orders',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => null,
            'features' => [
                ['title' => 'Excel order import', 'description' => 'Bring large order lists into the system quickly and accurately.'],
                ['title' => 'Location assignment', 'description' => 'Send each order to the right delivery person based on its location.'],
                ['title' => 'Order tracking', 'description' => 'Follow order progress across assignment, delivery and settlement.'],
                ['title' => 'Delivery management', 'description' => 'Coordinate delivery staff, workloads and completion status.'],
                ['title' => 'Customer ledgers', 'description' => 'Keep receivables, payments and account history connected to every order.'],
                ['title' => 'Financial statements', 'description' => 'Review balances and business performance through dependable reports.'],
            ],
        ],
        'rms' => [
            'name' => 'RMS',
            'eyebrow' => 'Restaurant & Food Business Management',
            'hero_focus' => 'modern restaurants and food businesses.',
            'tagline' => 'Run your restaurant from one connected workspace.',
            'description' => 'A complete restaurant management platform designed to bring your front desk, dining floor, kitchen and back-office operations together. Manage orders, tables, menu items, staff, customers, expenses and supplies without jumping between different systems.',
            'icon' => 'restaurant',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => 'http://187.127.204.45/rms-system/demo',
            'features' => [
                ['title' => 'Orders & payments', 'description' => 'Create and manage customer orders through a streamlined workflow while keeping payment and order history organized.'],
                ['title' => 'Kitchen operations', 'description' => 'Send and manage kitchen orders digitally so your service team and kitchen stay aligned from order placement to completion.'],
                ['title' => 'Table management', 'description' => 'Organize restaurant tables, monitor dining operations and keep table-based service easier to manage during busy hours.'],
                ['title' => 'Menu management', 'description' => 'Manage menu items from one place and keep your restaurant\'s available offerings organized and easy for staff to access.'],
                ['title' => 'Staff & attendance', 'description' => 'Manage employees, roles and attendance records so responsibilities and daily workforce activity remain clear.'],
                ['title' => 'Supplies & business insights', 'description' => 'Track restaurant supplies, stock movements and expenses while using dashboards and reports to understand daily business performance.'],
            ],
        ],
        'paddle' => [
            'name' => 'Paddle',
            'eyebrow' => 'Paddle Club Management',
            'hero_focus' => 'clubs that play smarter.',
            'tagline' => 'Make courts, teams and bookings effortless to manage.',
            'description' => 'A connected admin system and customer app for paddle clubs. Players can create teams and buy court time, while administrators control grounds, schedules, bookings and club operations.',
            'icon' => 'paddle',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => null,
            'features' => [
                ['title' => 'Court management', 'description' => 'Set up grounds, court availability, time slots and operating hours.'],
                ['title' => 'Customer app', 'description' => 'Let players explore availability and manage their activity on the go.'],
                ['title' => 'Team creation', 'description' => 'Make it easy for customers to create and organize their paddle teams.'],
                ['title' => 'Online bookings', 'description' => 'Allow players to select and purchase available court sessions.'],
                ['title' => 'Admin control', 'description' => 'Oversee users, bookings, grounds and day-to-day club operations.'],
                ['title' => 'Performance overview', 'description' => 'Understand usage and booking activity from a focused dashboard.'],
            ],
        ],
    ],
];
