<?php

return [
    'sales_email' => env('SOFTWARE_SALES_EMAIL', 'bill.humayun1@gmail.com'),
    'sales_phone' => env('SOFTWARE_SALES_PHONE', '+92 3003662818'),
    'products' => [
        'cloud-khata' => [
            'name' => 'Cloud Khata',
            'eyebrow' => 'Business & POS Management',
            'tagline' => 'Run your business with clarity, from counter to accounts.',
            'description' => 'A complete cloud-based business and point-of-sale system that brings sales, purchases, inventory, customers, suppliers and financial reporting into one reliable workspace.',
            'icon' => 'cloud',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => null,
            'features' => [
                ['title' => 'Fast point of sale', 'description' => 'Create accurate bills, accept payments and keep every sale organized.'],
                ['title' => 'Inventory control', 'description' => 'Monitor stock, purchases, transfers and low-stock alerts in real time.'],
                ['title' => 'Business accounts', 'description' => 'Track customer and supplier ledgers, expenses, dues and cash flow.'],
                ['title' => 'Actionable reporting', 'description' => 'Understand sales, profit, stock and business performance from clear reports.'],
                ['title' => 'Multi-user operations', 'description' => 'Give team members the right access while keeping control of the business.'],
                ['title' => 'Cloud access', 'description' => 'Stay connected to your operation wherever business takes you.'],
            ],
        ],
        'vendify' => [
            'name' => 'Vendify',
            'eyebrow' => 'Retail & Salon ERP',
            'tagline' => 'One intelligent workspace for modern retail and service businesses.',
            'description' => 'A flexible ERP and POS platform designed for salons, shops and growing retailers. Manage your employees, inventory, appointments, sales and customer experience without switching systems.',
            'icon' => 'store',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => 'https://pos.broshtech.com/',
            'features' => [
                ['title' => 'Salon & retail POS', 'description' => 'Serve walk-in and booked customers with a quick, intuitive checkout.'],
                ['title' => 'Employee management', 'description' => 'Organize staff, roles, schedules, attendance and performance.'],
                ['title' => 'Smart inventory', 'description' => 'Control products, purchasing, stock levels and supplier relationships.'],
                ['title' => 'Appointments', 'description' => 'Coordinate services and staff availability from one shared calendar.'],
                ['title' => 'Customer profiles', 'description' => 'Build loyalty with purchase history and useful customer records.'],
                ['title' => 'Business insights', 'description' => 'Use practical dashboards and reports to make stronger decisions.'],
            ],
        ],
        'cx-couriers' => [
            'name' => 'CX Couriers',
            'eyebrow' => 'Courier Operations',
            'tagline' => 'Deliver every parcel with control, speed and visibility.',
            'description' => 'An end-to-end courier management system for organizing bookings, delivery teams, service routes, customers, cash collection and account ledgers from dispatch to final delivery.',
            'icon' => 'courier',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => null,
            'features' => [
                ['title' => 'Delivery workflow', 'description' => 'Manage consignments from booking and dispatch through delivery completion.'],
                ['title' => 'Rider management', 'description' => 'Assign deliveries and coordinate your delivery team efficiently.'],
                ['title' => 'Route organization', 'description' => 'Structure service areas and routes for smoother daily operations.'],
                ['title' => 'Customer management', 'description' => 'Maintain complete shipper and recipient information in one place.'],
                ['title' => 'Cash & ledgers', 'description' => 'Track collections, customer balances, expenses and account activity.'],
                ['title' => 'Delivery reporting', 'description' => 'See delivery status, performance and financial results clearly.'],
            ],
        ],
        'doms' => [
            'name' => 'DOMS',
            'eyebrow' => 'Distributed Order Management',
            'tagline' => 'Turn spreadsheet orders into coordinated deliveries and clean accounts.',
            'description' => 'A distributed order management system that imports orders from Excel, assigns them to delivery staff by location and keeps delivery, ledger and financial records fully connected.',
            'icon' => 'orders',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => null,
            'features' => [
                ['title' => 'Excel order import', 'description' => 'Bring large order lists into the system quickly and accurately.'],
                ['title' => 'Location assignment', 'description' => 'Send each order to the right delivery person based on its location.'],
                ['title' => 'Order tracking', 'description' => 'Follow order progress across assignment, delivery and settlement.'],
                ['title' => 'Delivery management', 'description' => 'Coordinate delivery staff, workloads and completion status.'],
                ['title' => 'Customer ledgers', 'description' => 'Keep receivables, payments and account history connected to every order.'],
                ['title' => 'Financial statements', 'description' => 'Review balances and business performance through dependable reports.'],
            ],
        ],
        'rms' => [
            'name' => 'RMS',
            'eyebrow' => 'Restaurant Management',
            'tagline' => 'Everything your restaurant team needs—from table to payroll.',
            'description' => 'A complete restaurant management system for coordinating customers, waiters, kitchen staff, orders, payments, salaries and attendance across the entire restaurant operation.',
            'icon' => 'restaurant',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => null,
            'features' => [
                ['title' => 'Restaurant POS', 'description' => 'Handle tables, orders, billing and payments through a smooth workflow.'],
                ['title' => 'Waiter operations', 'description' => 'Assign tables, send orders and keep service teams coordinated.'],
                ['title' => 'Kitchen management', 'description' => 'Give cooks a clear, real-time view of incoming and active orders.'],
                ['title' => 'Customer accounts', 'description' => 'Manage customer history, balances and payment activity.'],
                ['title' => 'Payroll & salaries', 'description' => 'Keep staff compensation and workforce records organized.'],
                ['title' => 'Geofenced attendance', 'description' => 'Record attendance with location controls for better accountability.'],
            ],
        ],
        'paddle' => [
            'name' => 'Paddle',
            'eyebrow' => 'Paddle Club Management',
            'tagline' => 'Make courts, teams and bookings effortless to manage.',
            'description' => 'A connected admin system and customer app for paddle clubs. Players can create teams and buy court time, while administrators control grounds, schedules, bookings and club operations.',
            'icon' => 'paddle',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => null,
            'features' => [
                ['title' => 'Court management', 'description' => 'Set up grounds, court availability, time slots and operating hours.'],
                ['title' => 'Customer app', 'description' => 'Let players explore availability and manage their activity on the go.'],
                ['title' => 'Team creation', 'description' => 'Make it easy for customers to create and organize their paddle teams.'],
                ['title' => 'Online bookings', 'description' => 'Allow players to select and purchase available court sessions.'],
                ['title' => 'Admin control', 'description' => 'Oversee users, bookings, grounds and day-to-day club operations.'],
                ['title' => 'Performance overview', 'description' => 'Understand usage and booking activity from a focused dashboard.'],
            ],
        ],
    ],
];
