<?php

return [
    'sales_email' => env('SOFTWARE_SALES_EMAIL', 'bill.humayun1@gmail.com'),
    'sales_phone' => env('SOFTWARE_SALES_PHONE', '+92 3003662818'),
    'products' => [
        'cloud-khata' => [
            'name' => 'Cloud Khata',
            'eyebrow' => 'Business & POS Management',
            'hero_focus' => 'business that stays in control.',
            'tagline' => 'Run sales, stock and accounts from one connected system.',
            'description' => 'An all-in-one business management and POS platform for handling daily sales, inventory, purchases, customers, suppliers, expenses and financial activity without switching between different tools.',
            'demo_label' => 'Demo available',
            'dashboard_alt' => 'Cloud Khata business dashboard',
            'badge_text' => 'Simple. Connected. Organized.',
            'feature_focus' => 'Less manual work.',
            'feature_intro' => 'Core tools designed to simplify everyday operations, keep your records accurate and give you a clearer view of your business.',
            'cta_intro' => 'Keep every sale, stock movement and rupee connected.',
            'cta_heading' => 'Ready to run your business better with Cloud Khata?',
            'icon' => 'cloud',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => 'https://cloudkhata.broshtech.com/demo',
            'embed_enabled' => true,
            'features' => [
                ['title' => 'POS & sales', 'description' => 'Process daily sales, manage payments, create invoices and keep every transaction organized in one place.'],
                ['title' => 'Products & inventory', 'description' => 'Manage products, pricing and stock levels with stock history, adjustments, transfers and inventory alerts.'],
                ['title' => 'Purchases & suppliers', 'description' => 'Record purchases, manage suppliers, track purchase payments and keep incoming stock connected to your accounts.'],
                ['title' => 'Customers & ledgers', 'description' => 'Maintain customer and supplier records, monitor outstanding dues, record payments and review complete account ledgers.'],
                ['title' => 'Expenses & accounts', 'description' => 'Track business expenses, payment accounts, deposits, fund transfers, balances and cash movement with greater clarity.'],
                ['title' => 'Reports & insights', 'description' => 'Understand sales, purchases, stock, expenses, taxes and profitability through detailed business and financial reports.'],
            ],
        ],
        'vendify' => [
            'name' => 'Vendify',
            'eyebrow' => 'Retail & Service Management',
            'hero_focus' => 'modern retail and service businesses.',
            'tagline' => 'Run your entire business from one connected workspace.',
            'description' => 'A flexible POS and business management platform designed for shops, salons and service-based businesses. Manage sales, customers, inventory, employees, appointments, purchasing and daily operations without switching between multiple systems.',
            'icon' => 'store',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => 'https://pos.broshtech.com/demo',
            'embed_enabled' => true,
            'features' => [
                ['title' => 'Smart POS & sales', 'description' => 'Process sales quickly, manage payments, apply coupons and keep every transaction organized in one place.'],
                ['title' => 'Inventory & purchasing', 'description' => 'Track products, stock levels, low-stock alerts, suppliers, purchases and stock adjustments with better visibility.'],
                ['title' => 'Staff & HR management', 'description' => 'Manage employees, roles, permissions, attendance, shifts, leave requests, salaries and staff performance.'],
                ['title' => 'Appointments & services', 'description' => 'Organize appointments, services, packages and staff availability through a simple shared workflow.'],
                ['title' => 'Customers & suppliers', 'description' => 'Keep useful customer and supplier records together with sales, purchase and transaction history.'],
                ['title' => 'Reports & business insights', 'description' => 'Monitor sales, inventory, attendance, salaries, customer purchases and staff performance through practical reports and dashboards.'],
            ],
        ],
        'cx-couriers' => [
            'name' => 'CX Couriers',
            'eyebrow' => 'Courier Operations',
            'hero_focus' => 'fleets that keep moving.',
            'tagline' => 'Run every trip with control, clarity and confidence.',
            'description' => 'An integrated fleet and courier operations system for managing vehicles, drivers, daily trips, operating costs, customers, wages and financial performance from one connected workspace.',
            'demo_label' => 'Demo available',
            'dashboard_alt' => 'CX Couriers fleet management dashboard',
            'feature_intro' => 'Core tools designed to keep your fleet organized, your operations visible and your finances under control.',
            'cta_intro' => 'Bring smarter fleet operations within reach.',
            'icon' => 'courier',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => 'http://187.127.204.45/courier/demo',
            'embed_enabled' => true,
            'features' => [
                ['title' => 'Fleet management', 'description' => 'Manage vans, vehicle status, fixed costs and driver assignments from one place.'],
                ['title' => 'Trip operations', 'description' => 'Record daily trips, customers, routes, fares and vehicle activity with clear operational history.'],
                ['title' => 'Driver & wages', 'description' => 'Manage driver profiles, assignments, advances and wage payouts with accurate records.'],
                ['title' => 'Customers & stakeholders', 'description' => 'Organize customer accounts, drivers and investors with complete profiles and transaction history.'],
                ['title' => 'Expenses & ledgers', 'description' => 'Track fuel, maintenance, operating expenses and van or customer balances with connected ledgers.'],
                ['title' => 'Financial reporting', 'description' => 'Monitor revenue, expenses and profitability with trial balance, profit & loss and financial reports.'],
            ],
        ],
        'doms' => [
            'name' => 'DOMS',
            'eyebrow' => 'Distributed Order Management',
            'hero_focus' => 'distribution that stays in control.',
            'tagline' => 'Move every order from dispatch to settlement with clarity.',
            'description' => 'An end-to-end delivery order management system for organizing trips, invoices, delivery teams, market collections, stock returns and financial reconciliation from warehouse dispatch to final settlement.',
            'demo_label' => 'Demo available',
            'badge_text' => 'Simple. Connected. Accountable.',
            'feature_focus' => 'Less reconciliation.',
            'feature_intro' => 'Core tools designed to keep your deliveries organized, your stock traceable and every payment accounted for.',
            'cta_intro' => 'Keep every delivery, rupee and return accounted for.',
            'cta_heading' => 'Ready to run distribution better with DOMS?',
            'icon' => 'orders',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => 'http://187.127.204.45/doms-sytem/demo',
            'embed_enabled' => true,
            'features' => [
                ['title' => 'Trip & delivery workflow', 'description' => 'Manage delivery trips from preparation and dispatch through delivery results, collections and final closure.'],
                ['title' => 'Deliverymen & markets', 'description' => 'Track delivery teams, assigned market areas, trip performance and customer market activity in one place.'],
                ['title' => 'Invoices & collections', 'description' => 'Connect customer invoices with trips and record cash, cheque or bank transfer collections accurately.'],
                ['title' => 'Stock & returns', 'description' => 'Monitor SKU inventory, stock movement, low-stock levels and returned goods with clear movement history.'],
                ['title' => 'Settlements & shortages', 'description' => 'Reconcile expected cash against collections and expenses, then classify shortages before closing each trip.'],
                ['title' => 'Ledgers & reporting', 'description' => 'Review market balances, operational performance, stock movement and financial results through connected reports.'],
            ],
        ],
        'rms' => [
            'name' => 'RMS',
            'eyebrow' => 'Restaurant & Food Business Management',
            'hero_focus' => 'modern restaurants and food businesses.',
            'tagline' => 'Run your restaurant from one connected workspace.',
            'description' => 'A complete restaurant management platform designed to bring your front desk, dining floor, kitchen and back-office operations together. Manage orders, tables, menu items, staff, customers, expenses and supplies without jumping between different systems.',
            'icon' => 'restaurant',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => 'http://187.127.204.45/rms-system/demo',
            'embed_enabled' => true,
            'features' => [
                ['title' => 'Orders & payments', 'description' => 'Create and manage customer orders through a streamlined workflow while keeping payment and order history organized.'],
                ['title' => 'Kitchen operations', 'description' => 'Send and manage kitchen orders digitally so your service team and kitchen stay aligned from order placement to completion.'],
                ['title' => 'Table management', 'description' => 'Organize restaurant tables, monitor dining operations and keep table-based service easier to manage during busy hours.'],
                ['title' => 'Menu management', 'description' => 'Manage menu items from one place and keep your restaurant\'s available offerings organized and easy for staff to access.'],
                ['title' => 'Staff & attendance', 'description' => 'Manage employees, roles and attendance records so responsibilities and daily workforce activity remain clear.'],
                ['title' => 'Supplies & business insights', 'description' => 'Track restaurant supplies, stock movements and expenses while using dashboards and reports to understand daily business performance.'],
            ],
        ],
        'paddle' => [
            'name' => 'Padel POS',
            'eyebrow' => 'Padel Club Management',
            'hero_focus' => 'clubs that never stop moving.',
            'tagline' => 'One connected workspace for your entire padel club.',
            'description' => 'A modern club management and POS platform designed to handle court bookings, players, memberships, café sales, inventory and daily operations without juggling multiple systems.',
            'demo_label' => 'Demo available',
            'dashboard_alt' => 'Padel club management dashboard',
            'badge_heading' => 'One connected system',
            'badge_text' => 'Book. Play. Sell. Manage.',
            'feature_heading' => 'More court time.',
            'feature_focus' => 'Less admin work.',
            'feature_intro' => 'Core tools designed to keep your courts organized, your players connected and your club operations running smoothly.',
            'cta_intro' => 'Every court, player and sale — connected.',
            'cta_heading' => 'Ready to run your padel club smarter with Padel POS?',
            'icon' => 'paddle',
            'color' => '#222222',
            'soft_color' => '#ececea',
            'secondary_color' => '#d6d6d2',
            'accent_text' => '#ffffff',
            'demo_url' => 'http://187.127.204.45/padel/demo',
            'embed_enabled' => true,
            'features' => [
                ['title' => 'Court bookings & schedule', 'description' => 'Manage court availability, create bookings, prevent scheduling conflicts and keep every session organized through one shared schedule.'],
                ['title' => 'Players & teams', 'description' => 'Manage players, organize teams, track skill levels, team activity and match performance from one centralized workspace.'],
                ['title' => 'Café POS', 'description' => 'Sell drinks, snacks, bundles and café products through a simple checkout experience with inventory updated automatically after every sale.'],
                ['title' => 'Clients & memberships', 'description' => 'Maintain client profiles, create membership plans, enroll members and keep track of active memberships, visits and customer activity.'],
                ['title' => 'Products, stock & suppliers', 'description' => 'Manage café and padel products, monitor stock levels, identify low-stock items, record purchases and keep supplier balances organized.'],
                ['title' => 'Reports & club finances', 'description' => 'Monitor court revenue, café sales, expenses, purchases, bookings and player activity while keeping daily cash reconciliation and transaction history organized.'],
            ],
        ],
    ],
];
